package com.appbackend.example.AppBackend.enums;

public enum LoanReminder {

    ONE_DAY_AFTER_RESCHEDULED,
    ONE_WEEK_AFTER_RESCHEDULED,
    RESCHEDULED_DUE_DATE,
    DURING_PROCESS,
    ONE_DAY_AFTER_LOAN,
    PART_PAYMENT,
    TWO_WEEKS_AFTER_LOAN,
    ONE_WEEK_BEFORE,
    DUE_DATE,
    FULL_PAYMENT,
    NO_PAYMENT_OR_PAID_PART_PAYMENT_ON_DUE_DATE,
    ONE_DAY_AFTER_DUE,
    THREE_DAYS_AFTER_DUE,
    FIVE_DAYS_AFTER_DUE,
    SEVEN_DAYS_AFTER_DUE,
    NINE_DAYS_AFTER_DUE,
    ELEVEN_DAYS_AFTER_DUE,
    THIRTEEN_DAYS_AFTER_DUE,
    FIFTEEN_DAYS_AFTER_DUE,
    SEVENTEEN_DAYS_AFTER_DUE,
    NINETEEN_DAYS_AFTER_DUE,
    TWENTY_ONE_DAYS_AFTER_DUE,
    TWENTY_THREE_DAYS_AFTER_DUE,
    TWENTY_FIVE_DAYS_AFTER_DUE,
    TWENTY_SEVEN_DAYS_AFTER_DUE,
    TWENTY_NINE_DAYS_AFTER_DUE,
    THIRTY_DAYS_AFTER_DUE;

}
